- app/utils/ViewUtils.scala
- project/AppDependencies.scala
- test/utils/ViewUtilSpec.scala
Update displayed currency values to match GDS way
[SASS-1480](https://jira.tools.tax.service.gov.uk/browse/SASS-1480)
> Update displayed currency values to match GDS way

- app/controllers/pensions/PensionsSummaryController.scala
- app/controllers/pensions/PensionsTaxReliefNotClaimedController.scala
- app/controllers/pensions/RetirementAnnuityController.scala
- app/views/pensions/PayIntoRetirementAnnuityContractView.scala.html
- app/views/pensions/PensionsTaxReliefNotClaimedView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/PensionsTaxReliefNotClaimedControllerISpec.scala
- it/controllers/pensions/RetirementAnnuityControllerISpec.scala
- it/utils/PageUrls.scala
- test/forms/FormUtilsSpec.scala
Create 'did you pay into a pension where tax relief was not claimed' radio button page
[SASS-2051](https://jira.tools.tax.service.gov.uk/browse/SASS-2051)
- []  Have you run the journey tests? (where applicable)
> SASS-1946 Adding pension tax relief not paid question page

- app/controllers/pensions/PensionsTaxReliefNotClaimedController.scala
- app/controllers/pensions/ReliefAtSourcePensionsController.scala
- app/views/pensions/PayIntoRetirementAnnuityContractView.scala.html
- app/views/pensions/ReliefAtSourcePensionsView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/PensionsTaxReliefNotClaimedControllerISpec.scala
- it/controllers/pensions/ReliefAtSourcePensionsControllerISpec.scala
- it/utils/PageUrls.scala
Pensions (payments into) - Create 'did you pay into a RAS pension' radio button page
[SASS-1945](https://jira.tools.tax.service.gov.uk/browse/SASS-1945)
> SASS-1945 Create RAS pension radio button page

- app/controllers/pensions/ReliefAtSourcePaymentsAndTaxReliefAmountController.scala
- app/controllers/pensions/ReliefAtSourcePensionsController.scala
- app/views/pensions/PensionsTaxReliefNotClaimedView.scala.html
- app/views/pensions/ReliefAtSourcePaymentsAndTaxReliefAmountView.scala.html
- app/views/pensions/ReliefAtSourcePensionsView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/ReliefAtSourcePaymentsAndTaxReliefAmountControllerISpec.scala
- it/controllers/pensions/ReliefAtSourcePensionsControllerISpec.scala
- it/utils/PageUrls.scala
- it/utils/ViewHelpers.scala
Create 'total payments into RAS pensions' amount page
[SASS-1949](https://jira.tools.tax.service.gov.uk/browse/SASS-1949)
> SASS-1949 Add Total Ras Payments and tax relif amount page

- app/controllers/pensions/WorkplaceAmountController.scala
- app/models/mongo/PensionsUserData.scala
- app/views/pensions/PaymentsIntoPensionsCYAView.scala.html
- app/views/pensions/WorkplaceAmountView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/PaymentsIntoPensionsCYAControllerISpec.scala
- it/controllers/pensions/WorkplaceAmountControllerISpec.scala
- it/utils/PageUrls.scala
Implement workplace amount page
[SASS 2125](https://jira.tools.tax.service.gov.uk/browse/SASS-2125)
> SASS 2125 implemented workplace amount page

- app/controllers/pensions/WorkplacePensionController.scala
- app/views/pensions/PaymentsIntoPensionsCYAView.scala.html
- app/views/pensions/WorkplacePensionView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/PaymentsIntoPensionsCYAControllerISpec.scala
- it/controllers/pensions/WorkplaceAmountControllerISpec.scala
- it/controllers/pensions/WorkplacePensionControllerISpec.scala
- it/utils/PageUrls.scala
Create 'Pensions (payments into) - Did you pay into a workplace pension and not receive tax relief?' radio button page
[SASS-2124](https://jira.tools.tax.service.gov.uk/browse/SASS-2124)
> SASS-2124 Create workplace pension payments radio page

- app/controllers/pensions/PaymentsIntoPensionsCYAController.scala
- app/controllers/pensions/annualAllowance/ReducedAnnualAllowanceTypeController.scala
- app/forms/ReducedAnnualAllowanceTypeQuestionForm.scala
- app/utils/StatusHelper.scala
- app/views/pensions/annualAllowance/ReducedAnnualAllowanceTypeView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/annualAllowance/ReducedAnnualAllowanceTypeControllersControllerISpec.scala
- it/utils/PageUrls.scala
- it/utils/ViewHelpers.scala
- project/AppDependencies.scala
- test/builders/PensionsUserDataBuilder.scala
Create 'What type of reduced annual allowance do you have? page
[SASS-SASS-2298](https://jira.tools.tax.service.gov.uk/browse/SASS-2298)
> SASS-2298 Create What type of reduced allowance page

- app/controllers/pensions/annualAllowance/ReducedAnnualAllowanceController.scala
- app/models/mongo/PensionsCYAModel.scala
- app/views/pensions/annualAllowance/ReducedAnnualAllowanceTypeView.scala.html
- app/views/pensions/annualAllowance/ReducedAnnualAllowanceView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/annualAllowance/ReducedAnnualAllowanceControllerISpec.scala
- it/utils/PageUrls.scala
Create 'Do you have a reduced annual allowance?' page
[SASS-2297](https://jira.tools.tax.service.gov.uk/browse/SASS-2297)
> SASS-2297 Reduced Annual Allowance radio page

- app/controllers/pensions/annualAllowance/AboveReducedAnnualAllowanceController.scala
- app/controllers/pensions/annualAllowance/ReducedAnnualAllowanceController.scala
- app/controllers/pensions/annualAllowance/ReducedAnnualAllowanceTypeController.scala
- app/views/pensions/annualAllowance/AboveReducedAnnualAllowanceView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/annualAllowance/AboveReducedAnnualAllowanceControllerISpec.scala
- it/controllers/pensions/annualAllowance/ReducedAnnualAllowanceControllerISpec.scala
- it/controllers/pensions/annualAllowance/ReducedAnnualAllowanceTypeControllersControllerISpec.scala
- it/utils/PageUrls.scala
Pensions annual allowance - Create' Have you gone above your reduced annual allowance? page
[SASS-2299](https://jira.tools.tax.service.gov.uk/browse/SASS-2299)
> SASS-2299A Above Reduced Annual Allowance Page

- project/AppDependencies.scala
[SASS-2549](https://jira.tools.tax.service.gov.uk/browse/SASS-2009)
> [DM] [SASS-2549] Updating dependencies

- app/assets/stylesheets/application.scss
- project/AppDependencies.scala
[SASS-2332](https://jira.tools.tax.service.gov.uk/browse/SASS-2332)
> [SASS-2332] Back link and language toggle layout

- app/common/AnnualAllowanceTaxPaidValues.scala
- app/controllers/pensions/annualAllowance/AboveReducedAnnualAllowanceAmountController.scala
- app/controllers/pensions/annualAllowance/PensionProviderPaidTaxController.scala
- app/controllers/pensions/paymentsIntoPension/PaymentsIntoPensionsCYAController.scala
- app/forms/PensionProviderPaidTaxQuestionForm.scala
- app/views/pensions/annualAllowance/PensionProviderPaidTaxView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/annualAllowance/AboveReducedAnnualAllowanceAmountControllerISpec.scala
- it/controllers/pensions/annualAllowance/PensionProviderPaidTaxControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/PaymentsIntoPensionsCYAControllerISpec.scala
- it/utils/PageUrls.scala
- project/AppDependencies.scala
Implemented pension provider paid 
[SASS-2301](https://jira.tools.tax.service.gov.uk/browse/SASS-2301)
> SASS-2301 Implemented PensionProviderPaid

- app/assets/stylesheets/itsa-print.css
- app/views/templates/Head.scala.html
- app/views/templates/Layout.scala.html
- project/AppDependencies.scala
SASS-2523 fix to print preview styling.
[SASS-2523](https://jira.tools.tax.service.gov.uk/browse/SASS-2523)
> SASS-2523 print preview styling

- app/controllers/pensions/annualAllowance/PensionProviderPaidTaxController.scala
- app/forms/PensionProviderPaidTaxQuestionForm.scala
- app/views/pensions/annualAllowance/PensionProviderPaidTaxView.scala.html
- it/controllers/pensions/annualAllowance/PensionProviderPaidTaxControllerISpec.scala
Add page navigation for provide question and amount
Clear amount if question is No 
add extra tests for clearing amount
[SASS-2302](https://jira.tools.tax.service.gov.uk/browse/SASS-2302)
> SASS-2302A - wire up pages and fix amount clearing on provide paid tax

- app/controllers/pensions/annualAllowance/PensionSchemeTaxReferenceController.scala
- app/forms/PensionSchemeTaxReferenceForm.scala
- app/views/pensions/annualAllowance/PensionSchemeTaxReferenceView.scala.html
- app/views/pensions/annualAllowance/TaxPaidByPensionProviderAmountView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/annualAllowance/PensionSchemeTaxReferenceControllerISpec.scala
- it/utils/PageUrls.scala
[SASS-2303](https://jira.tools.tax.service.gov.uk/browse/SASS-2303)
> Implemented Pension Scheme Tax Reference page

- app/controllers/pensions/paymentsIntoPension/OneOffRASPaymentsAmountController.scala
- app/controllers/pensions/paymentsIntoPension/PaymentsIntoPensionsCYAController.scala
- app/controllers/pensions/paymentsIntoPension/PensionsTaxReliefNotClaimedController.scala
- app/controllers/pensions/paymentsIntoPension/ReliefAtSourceOneOffPaymentsController.scala
- app/controllers/pensions/paymentsIntoPension/ReliefAtSourcePaymentsAndTaxReliefAmountController.scala
- app/controllers/pensions/paymentsIntoPension/ReliefAtSourcePensionsController.scala
- app/controllers/pensions/paymentsIntoPension/RetirementAnnuityAmountController.scala
- app/controllers/pensions/paymentsIntoPension/RetirementAnnuityController.scala
- app/controllers/pensions/paymentsIntoPension/TotalPaymentsIntoRASController.scala
- app/controllers/pensions/paymentsIntoPension/WorkplaceAmountController.scala
- app/controllers/pensions/paymentsIntoPension/WorkplacePensionController.scala
- app/models/redirects/ConditionalRedirect.scala
- app/services/RedirectService.scala
- app/utils/PaymentsIntoPensionPages.scala
- it/controllers/pensions/paymentsIntoPensions/OneOffRASPaymentsAmountControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/PaymentsIntoPensionsCYAControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/PensionsTaxReliefNotClaimedControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/ReliefAtSourceOneOffPaymentsControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/ReliefAtSourcePaymentsAndTaxReliefAmountControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/ReliefAtSourcePensionsControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/RetirementAnnuityAmountControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/RetirementAnnuityControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/TotalPaymentsIntoRASControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/WorkplacePensionControllerISpec.scala
[SASS-2097](https://jira.tools.tax.service.gov.uk/browse/SASS-2097)
> [SASS-2097] - payments into pension navigation

- app/controllers/pensions/incomeFromPensions/StatePensionLumpSumAmountController.scala
- app/views/pensions/incomeFromPensions/StatePensionLumpSumAmountView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/StatePensionLumpSumAmountControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/RetirementAnnuityAmountControllerISpec.scala
- it/utils/PageUrls.scala
> SASS-2055 lump sum amount page

- app/controllers/pensions/incomeFromPensions/TaxPaidOnStatePensionLumpSumController.scala
- app/views/pensions/incomeFromPensions/TaxPaidOnStatePensionLumpSumView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/StatePensionLumpSumAmountControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/TaxPaidOnStatePensionLumpSumControllerISpec.scala
- it/utils/PageUrls.scala
- test/builders/PensionsUserDataBuilder.scala
Create 'Did you pay tax on the State Pension lump sum?' page
[SASS-2056](https://jira.tools.tax.service.gov.uk/browse/SASS-2056)
See the following also for stub data:
[Stub data for EOY pension user](https://github.com/hmrc/income-tax-submission-stub/pull/112)
> SASS-2056 - add tax paid on lump sum page

- app/controllers/pensions/incomeFromPensions/StatePensionController.scala
- app/views/pensions/incomeFromPensions/StatePensionView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/pensionIncome/StatePensionControllerISpec.scala
- it/utils/PageUrls.scala
Implement "did you get state benefits" page
[SASS-2901](https://jira.tools.tax.service.gov.uk/browse/SASS-2901)
> SASS-2091 Implement state pension page

- app/controllers/pensions/incomeFromPensions/StatePensionAmountController.scala
- app/views/pensions/incomeFromPensions/StatePensionAmountView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/StatePensionAmountControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/StatePensionControllerISpec.scala
- it/utils/PageUrls.scala
State pension amount page
[SASS-1964](https://jira.tools.tax.service.gov.uk/browse/SASS-1964)
> SASS-1964 State pension amount page

- conf/app.routes
- it/controllers/pensions/annualAllowance/AboveReducedAnnualAllowanceAmountControllerISpec.scala
- it/controllers/pensions/annualAllowance/AboveReducedAnnualAllowanceControllerISpec.scala
- it/controllers/pensions/annualAllowance/ReducedAnnualAllowanceControllerISpec.scala
- it/controllers/pensions/annualAllowance/ReducedAnnualAllowanceTypeControllersControllerISpec.scala
- it/utils/PageUrls.scala
Updated URLs for dynamic pages 
[SASS-2655](https://jira.tools.tax.service.gov.uk/browse/SASS-2655)
> SASS-2655 Updated URLs

- app/controllers/pensions/incomeFromPensions/StatePensionAmountController.scala
- app/controllers/pensions/incomeFromPensions/StatePensionController.scala
- app/controllers/pensions/incomeFromPensions/StatePensionLumpSumAmountController.scala
- app/controllers/pensions/incomeFromPensions/TaxPaidOnLumpSumAmountController.scala
- app/controllers/pensions/incomeFromPensions/TaxPaidOnStatePensionLumpSumController.scala
- app/views/pensions/incomeFromPensions/TaxPaidOnLumpSumAmountView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/StatePensionAmountControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/StatePensionControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/StatePensionLumpSumAmountControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/TaxPaidOnLumpSumAmountControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/TaxPaidOnStatePensionLumpSumControllerISpec.scala
- it/utils/PageUrls.scala
Create 'How much tax did you pay on the State Pension lump sum?' page
Also added dynamic content to State Pension Amount page
[SASS-2057](https://jira.tools.tax.service.gov.uk/browse/SASS-2057)
> SASS-2057 State Pension Lump Sum Tax Paid Amount

- app/filters/InputFilters.scala
- app/forms/PensionSchemeTaxReferenceForm.scala
- test/filters/InputFiltersSpec.scala
[SASS-2874](https://jira.tools.tax.service.gov.uk/browse/SASS-2874)
> SASS-2874 : Added input filters for text input forms

- app/controllers/pensions/incomeFromPensions/StatePensionController.scala
- app/controllers/pensions/incomeFromPensions/UkPensionIncomeSummaryController.scala
- app/views/pensions/annualAllowance/PstrSummaryView.scala.html
- app/views/pensions/incomeFromPensions/UkPensionIncomeSummary.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/UkPensionIncomeSummaryControllerISpec.scala
- it/utils/PageUrls.scala
income from pensions - Create 'UK pension income' task list (summary list page) 
[SASS-2180](https://jira.tools.tax.service.gov.uk/browse/SASS-2180)
> Sass 2180 - Create 'UK pension income' task list (summary list page)

- app/controllers/pensions/annualAllowance/PensionSchemeTaxReferenceController.scala
- app/controllers/pensions/incomeFromPensions/PensionSchemeDetailsController.scala
- app/controllers/pensions/incomeFromPensions/UkPensionSchemePaymentsController.scala
- app/forms/PensionSchemeDetailsForm.scala
- app/views/pensions/incomeFromPensions/PensionSchemeDetailsView.scala.html
- app/views/pensions/incomeFromPensions/UkPensionIncomeSummary.scala.html
- app/views/templates/helpers/InputTextAlt.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/PensionSchemeDetailsControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/UkPensionIncomeSummaryControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/UkPensionSchemePaymentsControllerISpec.scala
- it/utils/PageUrls.scala
- it/utils/ViewHelpers.scala
Create 'Pensions scheme details' page
[SASS-2181](https://jira.tools.tax.service.gov.uk/browse/SASS-2181)
> SASS-2181 create Pension Scheme Details page

- app/controllers/pensions/incomeFromPensions/PensionAmountController.scala
- app/controllers/pensions/incomeFromPensions/UkPensionSchemePaymentsController.scala
- app/forms/TupleAmountForm.scala
- app/forms/validation/mappings/Formatters.scala
- app/forms/validation/mappings/MappingUtil.scala
- app/views/pensions/incomeFromPensions/PensionAmountView.scala.html
- app/views/templates/helpers/InputTextAlt.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/PensionAmountControllerISpec.scala
- it/utils/PageUrls.scala
Pension Amount Page
[SASS-2704](https://jira.tools.tax.service.gov.uk/browse/SASS-2704)
> SASS-2704 pension amount page

- app/controllers/pensions/incomeFromPensions/PensionAmountController.scala
- app/controllers/pensions/incomeFromPensions/PensionSchemeDetailsController.scala
- app/controllers/pensions/incomeFromPensions/PensionSchemeStartDateController.scala
- app/forms/PensionSchemeDateForm.scala
- app/utils/DateTimeUtil.scala
- app/views/pensions/incomeFromPensions/PensionAmountView.scala.html
- app/views/pensions/incomeFromPensions/PensionSchemeStartDateView.scala.html
- app/views/templates/helpers/DateInput.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/PensionAmountControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/PensionSchemeDetailsControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/PensionSchemeStartDateControllerISpec.scala
- it/utils/PageUrls.scala
[SASS-2703](https://jira.tools.tax.service.gov.uk/browse/SASS-2703)
> SASS-2703 Pension scheme start date page

- app/controllers/pensions/lifetimeAllowance/PensionLumpSumController.scala
- app/views/pensions/lifetimeAllowance/PensionLumpSumView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/lifetimeAllowance/PensionLumpSumControllerISpec.scala
- it/utils/PageUrls.scala
- test/builders/PensionAnnualAllowanceViewModelBuilder.scala
- test/builders/PensionLifetimeAllowanceViewModelBuilder.scala
- test/builders/PensionsUserDataBuilder.scala
Implement Pension Lump Sum page for lifetime allowance flow. 
[SASS-2417](https://jira.tools.tax.service.gov.uk/browse/SASS-2417
> SASS-2655 Implemented Pension Lump Sum page

- app/controllers/pensions/incomeFromPensions/RemovePensionSchemeController.scala
- app/views/pensions/incomeFromPensions/RemovePensionSchemeView.scala.html
- app/views/pensions/incomeFromPensions/UkPensionIncomeSummary.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/RemovePensionSchemeControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/UkPensionIncomeSummaryControllerISpec.scala
- it/utils/PageUrls.scala
- project/AppDependencies.scala
> [SASS-2182] - added removePensionScheme page

- app/controllers/pensions/lifetimeAllowance/AboveAnnualLifeTimeAllowanceController.scala
- app/views/pensions/annualAllowance/AboveReducedAnnualAllowanceView.scala.html
- app/views/pensions/lifetimeAllowance/AboveAnnualLifeTimeAllowanceView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/lifetimeAllowance/AboveAnnualLifeTimeAllowanceControllerISpec.scala
- it/utils/PageUrls.scala
Create ' Have you gone above your life time allowance? page
[SASS-2416](https://jira.tools.tax.service.gov.uk/browse/SASS-2416)
> SASS-2416 create have you gone above lifetime allowance page

- app/controllers/pensions/incomeFromPensions/UkPensionSchemePaymentsController.scala
- app/models/mongo/PensionsCYAModel.scala
- app/models/pension/charges/UnauthorisedPaymentsViewModel.scala
- app/services/EncryptionService.scala
- app/services/PensionSessionService.scala
- it/controllers/pensions/incomeFromPensions/UkPensionSchemePaymentsControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/PaymentsIntoPensionsCYAControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/RetirementAnnuityControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/TotalPaymentsIntoRASControllerISpec.scala
- it/repositories/PensionsUserDataRepositoryISpec.scala
- it/utils/PensionDataStubs.scala
- test/builders/PensionsCYAModelBuilder.scala
- test/builders/UnauthorisedPaymentsViewModelBuilder.scala
Create unauthorised payments view model
Changed redirect on Uk Pension Scheme Payments page to render the page (as it is the first page in the journey) and prevent redirecting to CYA page if no session data which causes it to loop forever
[SASS-2507](https://jira.tools.tax.service.gov.uk/browse/SASS-2507)
> SASS-2507 create unauthorised payments view model

- app/controllers/pensions/unauthorisedPayments/DidYouPayNonUkTaxController.scala
- app/forms/RadioButtonAmountForm.scala
- app/views/pensions/unauthorisedPayments/DidYouPayNonUKTaxSurchargeView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/unauthorisedPayments/DidYouPayNonUkTaxControllerISpec.scala
- it/utils/PageUrls.scala
[SASS-2452](https://jira.tools.tax.service.gov.uk/browse/SASS-2452)
> SASS-2452 did you pay non-uk tax surcharge page

- app/models/pension/reliefs/PensionReliefsViewModel.scala
- app/services/EncryptionService.scala
- app/services/PensionSessionService.scala
- app/views/pensions/paymentsIntoPensions/PaymentsIntoPensionsCYAView.scala.html
- conf/messages
- conf/messages.cy
- it/controllers/pensions/paymentsIntoPensions/PaymentsIntoPensionsCYAControllerISpec.scala
- it/utils/PensionDataStubs.scala
- test/builders/PaymentsIntoPensionVewModelBuilder.scala
- test/builders/PensionsCYAModelBuilder.scala
- test/views/PaymentsIntoPensionsCYATestSupport.scala
Add gateway question line to pensions CYA page.
[SASS-2952](https://jira.tools.tax.service.gov.uk/browse/SASS-2952)
> SASS-2952: Add Payments into Pensions Gateway page question line to the CYA page

- it/controllers/pensions/PensionsSummaryControllerISpec.scala
- it/utils/IntegrationTest.scala
- project/AppDependencies.scala
[SASS-3123](https://jira.tools.tax.service.gov.uk/browse/SASS-3123)
> SASS-3123 - Update bootstrap-BE/FE-play-28 dependencies.

- app/controllers/pensions/unauthorisedPayments/DidYouPayNonUkTaxController.scala
- app/controllers/pensions/unauthorisedPayments/NonUkTaxOnAmountNotSurchargeController.scala
- app/forms/RadioButtonAmountForm.scala
- app/views/pensions/unauthorisedPayments/DidYouPayNonUKTaxSurchargeView.scala.html
- app/views/pensions/unauthorisedPayments/NonUkTaxOnAmountNotSurchargeView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/unauthorisedPayments/NonUkTaxOnAmountNotSurchargeControllerISpec.scala
- it/utils/PageUrls.scala
[SASS-2954] Did you pay non-UK tax on the amount that did not result in a surcharge? page
> SASS-2954 Did you pay non-UK tax on the amount that did not result in a surcharge? page

- app/controllers/pensions/incomeFromPensions/IncomeFromPensionsGatewayController.scala
- app/forms/IncomeFromPensionFormProvider.scala
- app/views/pensions/incomeFromPensions/IncomeFromPensionsGatewayView.scala.html
- app/views/pensions/incomeFromPensions/StatePensionAmountView.scala.html
- app/views/pensions/incomeFromPensions/StatePensionLumpSumAmountView.scala.html
- app/views/pensions/incomeFromPensions/StatePensionLumpSumView.scala.html
- app/views/pensions/incomeFromPensions/StatePensionView.scala.html
- app/views/pensions/incomeFromPensions/TaxPaidOnLumpSumAmountView.scala.html
- app/views/pensions/incomeFromPensions/TaxPaidOnStatePensionLumpSumView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/IncomeFromPensionsGatewayControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/StatePensionAmountControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/StatePensionControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/StatePensionLumpSumAmountControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/StatePensionLumpSumControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/TaxPaidOnLumpSumAmountControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/TaxPaidOnStatePensionLumpSumControllerISpec.scala
- project/AppDependencies.scala
- test/views/incomeFromPensions/IncomeFromPensionsGatewayTestSupport.scala
Create a Income from pensions gateway page
[SASS-2897](https://jira.tools.tax.service.gov.uk/browse/SASS-2897)
> SASS-2897: Income from pensions gateway page

- app/controllers/pensions/lifetimeAllowance/AnnualLifetimeAllowanceGatewayController.scala
- app/views/pensions/lifetimeAllowance/AnnualLifetimeAllowanceGatewayView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/lifetimeAllowance/AnnualLifetimeAllowanceControlllerISpec.scala
- test/views/AnnualLifetimeAllowanceGatewayTestSupport.scala
> [SASS-2939] Pensions - annual and lifetime allowance gateway page

- app/models/mongo/PensionsCYAModel.scala
- app/models/pension/charges/PaymentsIntoOverseasPensionsViewModel.scala
- app/services/EncryptionService.scala
- app/services/PensionSessionService.scala
- it/controllers/pensions/paymentsIntoPensions/PaymentsIntoPensionsCYAControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/TotalPaymentsIntoRASControllerISpec.scala
- it/repositories/PensionsUserDataRepositoryISpec.scala
- it/utils/PensionDataStubs.scala
- project/AppDependencies.scala
- test/builders/PaymentsIntoOverseasPensionsViewModelBuilder.scala
- test/builders/PensionsCYAModelBuilder.scala
[SASS-2508](https://jira.tools.tax.service.gov.uk/browse/SASS-2508)
> [SASS-2508] Create view model for pensions

- app/controllers/pensions/employmentFinancedRetirementScheme/BenefitsFromSchemeController.scala
- app/views/pensions/employmentFinancedRetirementScheme/BenefitsFromSchemeView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/employmentFinancedRetirementScheme/BenefitsFromSchemeControllerISpec.scala
- test/views/BenefitsFromSchemeTestSupport.scala
Create pensions EFRBS gateway page.
[SASS-2949](https://jira.tools.tax.service.gov.uk/browse/SASS-2949)
> SASS-2949: Pensions - EFRBS gateway page

- app/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentController.scala
- app/views/pensions/unauthorisedPayments/UnauthorisedPaymentView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/unauthorisedPayments/DidYouPayNonUkTaxControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/NonUkTaxOnAmountNotSurchargeControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/SurchargeAmountControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/WhereAnyOfTheUnauthorisedPaymentsControllerISpec.scala
- test/views/UnauthorisedPaymentTestSupport.scala
Create pensions unauthorised payment gateway page.
[SASS-2940](https://jira.tools.tax.service.gov.uk/browse/SASS-2940)
> SASS-2940: Pensions - unauthorised payment gateway page

- app/controllers/pensions/lifetimeAllowance/LifeTimeAllowanceAnotherWayController.scala
- app/controllers/pensions/lifetimeAllowance/PensionLumpSumDetailsController.scala
- app/controllers/pensions/lifetimeAllowance/PensionTakenAnotherWayAmountController.scala
- app/views/pensions/lifetimeAllowance/PensionTakenAnotherWayAmountView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/lifetimeAllowance/LifeTimeAllowanceAnotherWayControllerISpec.scala
- it/controllers/pensions/lifetimeAllowance/PensionTakenAnotherWayAmountControllerISpec.scala
- it/utils/PageUrls.scala
Your pension taken in another way page
[SASS-2495](https://jira.tools.tax.service.gov.uk/browse/SASS-2465)
> SASS-2465 pension another way amount

- app/connectors/ExcludeJourneyConnector.scala
- app/connectors/httpParsers/ExcludeJourneyHttpParser.scala
- app/services/ExcludeJourneyService.scala
- it/connectors/ExcludeJourneyConnectorISpec.scala
- project/AppDependencies.scala
> [SASS-3210] Added Exclude Journey Connector

- app/controllers/pensions/paymentsIntoOverseasPensions/PaymentIntoPensionScheme.scala
- app/views/pensions/paymentsIntoOverseasPensions/PaymentIntoPensionSchemeView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/paymentsIntoOverseasPensions/PaymentIntoPensionSchemeControllerISpec.scala
- it/utils/PageUrls.scala
payment into overseas page 
[SASS-2582](https://jira.tools.tax.service.gov.uk/browse/SASS-2582)
> SASS-2582 overseas payments

- app/controllers/pensions/annualAllowance/ReducedAnnualAllowanceController.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/EmployerPayOverseasPensionController.scala
- app/views/pensions/paymentsIntoOverseasPensions/EmployerPayOverseasPensionView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/paymentsIntoOverseasPensions/EmployerPayOverseasPensionControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/NoSurchargeAmountControllerISpec.scala
- it/utils/CommonUtils.scala
- it/utils/PageUrls.scala
- test/builders/PensionsUserDataBuilder.scala
[SASS-2583](https://jira.tools.tax.service.gov.uk/browse/SASS-2583)
> Implemented Employer pay overseas pension page

- .github/PULL_REQUEST_TEMPLATE.md
[SASS-3339](https://jira.tools.tax.service.gov.uk/browse/SASS-3339)
> [SASS-3339] Updated based on recent changed to ways of working.

- app/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAController.scala
- app/views/pensions/incomeFromPensions/UkPensionIncomeCYAView.scala.html
- app/views/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAView.scala.html
- app/views/pensions/unauthorisedPayments/UnauthorisedPaymentsView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAControllerISpec.scala
- it/utils/PageUrls.scala
- run_before_making_pr.sh
- []  Have you checked code coverage isn’t lower than previously?
> [SASS-2468] - Create' Check your unauthorised payments page

- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
Jira subtask: [SASS-3370](https://jira.tools.tax.service.gov.uk/browse/SASS-3370)
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3235 update library dependencies

- app/controllers/pensions/OverseasPensionsSummaryController.scala
- app/utils/StatusHelper.scala
- app/views/pensions/OverseasPensionsSummaryView.scala.html
- app/views/pensions/PensionsSummaryView.scala.html
- app/views/templates/helpers/Heading.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/OverseasPensionsSummaryControllerISpec.scala
- it/utils/CommonUtils.scala
- it/utils/PageUrls.scala
- test/config/MessagesSpec.scala
Jira subtask: SASS-3327
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3308 Add the overseas pensions summary page

- app/controllers/pensions/incomeFromPensions/IncomeFromPensionsSummaryController.scala
- app/utils/StatusHelper.scala
- app/views/pensions/incomeFromPensions/IncomeFromPensionsSummaryView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/IncomeFromPensionsSummaryControllerISpec.scala
- it/utils/PageUrls.scala
Jira subtask: SASS-3326
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3326] - Create Pension Income Summary Page

- app/controllers/pensions/unauthorisedPayments/UnAuthorisedPaymentsController.scala
- app/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAViewHelper.scala
- app/models/pension/charges/UnauthorisedPaymentsViewModel.scala
- app/views/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAView.scala.html
- test/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAViewHelperTest.scala
Jira subtask: SASS-2468
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-2468] Fixed bugs

- app/views/pensions/OverseasPensionsSummaryView.scala.html
- it/controllers/pensions/OverseasPensionsSummaryControllerISpec.scala
Jira subtask: [SASS-3327](https://jira.tools.tax.service.gov.uk/browse/SASS-3327)
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3308 fix link for payments into overseas pensions to route to the paymentIntoPensionScheme

- app/models/pension/AllPensionsData.scala
- app/models/pension/charges/PaymentsIntoOverseasPensionsViewModel.scala
- app/models/pension/income/PensionIncome.scala
- it/controllers/pensions/OverseasPensionsSummaryControllerISpec.scala
- it/utils/PensionDataStubs.scala
- test/builders/AllPensionsDataBuilder.scala
- test/builders/PaymentsIntoOverseasPensionsViewModelBuilder.scala
- test/builders/PensionIncomeViewModelBuilder.scala
- test/builders/PensionsCYAModelBuilder.scala
- test/services/PensionSessionServiceTest.scala
Jira subtask: SASS-3248
Have you ...
Have you ...
Have you ...
Have you ...
> SASS 3251 - Update All Pension Data to include pension income 

- app/controllers/pensions/paymentsIntoOverseasPensions/PaymentIntoPensionScheme.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/PaymentIntoPensionSchemeControllerISpec.scala
Jira subtask: SASS-3429
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3429 Bug fix for PaymentIntoPensionScheme

- app/controllers/pensions/unauthorisedPayments/UnAuthorisedPaymentsController.scala
- app/models/pension/charges/UnauthorisedPaymentsViewModel.scala
- it/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsControllerISpec.scala
- test/models/pensions/charges/UnauthorisedPaymentsViewModelSpec.scala
Jira subtask: [SASS-3528](https://jira.tools.tax.service.gov.uk/browse/SASS-3528)
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3400 remove CYA data related to surcharges when the question has been marked back as 'no'

- app/controllers/pensions/paymentsIntoOverseasPensions/TaxEmployerPaymentsController.scala
- app/views/pensions/paymentsIntoOverseasPensions/TaxEmployerPaymentsView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/paymentsIntoOverseasPensions/TaxEmployerPaymentsControllerISpec.scala
- it/utils/PageUrls.scala
Jira subtask: SASS-3234
Have you ...
Have you ...
Have you ...
Have you ...
> SASS 2586 - Implemented Tax Employer Payments page

- it/controllers/ControllerSpec.scala
- it/controllers/YesNoAmountControllerSpec.scala
- it/controllers/pensions/lifetimeAllowance/PensionProviderPaidTaxControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/PaymentIntoPensionSchemeControllerISpec.scala
Jira subtask: SASS-3647
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3640] Upgraded PaymentIntoPensionSchemeControllerISpec to new pattern.

- app/controllers/pensions/lifetimeAllowance/AnnualAndLifetimeAllowanceCYAViewHelper.scala
- app/controllers/pensions/lifetimeAllowance/AnnualLifetimeAllowanceCYAController.scala
- app/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAViewHelper.scala
- app/models/pension/AllPensionsData.scala
- app/utils/CYABaseHelper.scala
- app/views/pensions/lifetimeAllowance/AnnualAllowanceAndLifetimeAllownaceCYAView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/lifetimeAllowance/AnnualLifetimeAllowanceCYAControllerISpec.scala
- it/utils/PageUrls.scala
- it/utils/ViewHelpers.scala
- test/builders/PensionsUserDataBuilder.scala
- test/controllers/pensions/lifetimeAllowance/AnnualAndLifetimeAllowanceCYAViewHelperTest.scala
Jira subtask: SASS-2226
Have you ...
Have you ...
Have you ...
Have you ...
> Sass 2226 - Implement Annual and Lifetime Allowance CYA Page

- app/controllers/pensions/paymentsIntoOverseasPensions/QOPSReferenceController.scala
- app/forms/QOPSReferenceNumberForm.scala
- app/views/pensions/paymentsIntoOverseasPensions/QOPSReferenceView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/OverseasPensionsSummaryControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/EmployerPayOverseasPensionControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/QOPSReferenceControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/TaxEmployerPaymentsControllerISpec.scala
- it/utils/PageUrls.scala
- test/forms/QOPSReferenceNumberFormSpec.scala
Jira subtask: SASS-3238
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3238 Implemented QOPS reference page

- it/controllers/ControllerSpec.scala
- it/controllers/YesNoAmountControllerSpec.scala
- it/controllers/YesNoControllerSpec.scala
- it/controllers/pensions/lifetimeAllowance/PensionProviderPaidTaxControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/PaymentIntoPensionSchemeControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/PensionsTaxReliefNotClaimedControllerISpec.scala
Jira subtask: SASS-3697
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3696] Upgraded integration test for page: 'Pensions where tax relief is not claimed'.

- it/controllers/ControllerSpec.scala
- it/controllers/YesNoAmountControllerSpec.scala
- it/controllers/YesNoControllerSpec.scala
- it/controllers/pensions/incomeFromOverseasPensions/PensionOverseasIncomeStatusISpec.scala
- it/controllers/pensions/lifetimeAllowance/PensionProviderPaidTaxControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/PaymentIntoPensionSchemeControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/PensionsTaxReliefNotClaimedControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/UnauthorisedPensionSchemeTaxReferenceControllerISpec.scala
Various refactoring to make other scenarios more succinct.
Removed unnecessary variations of summaries where the user type + preferred language was irrelevant.
Jira subtask: SASS-3720
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3718] Upgraded UnauthorisedPensionSchemeTaxReferenceControllerISpec to new pattern.

- it/controllers/ControllerSpec.scala
- it/controllers/pensions/unauthorisedPayments/DidYouPayNonUkTaxControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/NonUkTaxOnAmountNotSurchargeControllerISpec.scala
Both tests are against pages which follow the 'yes/no/amount' pattern.
Note that these tests as they are now, document several subtle bugs which will be addressed in subsequent stories.
Jira subtask: SASS-3829
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3817] Upgraded two integration tests.

- app/controllers/predicates/AuthorisedAction.scala
- it/helpers/WireMockHelper.scala
- it/utils/IntegrationTest.scala
- test/controllers/predicates/AuthorisedActionSpec.scala
- test/support/mocks/MockAuthorisedAction.scala
- test/utils/UnitTest.scala
Jira subtask: SASS-3946
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3946 Increase the 'Confidence Level' to 250 from 200

- app/controllers/pensions/incomeFromOverseasPensions/PensionOverseasIncomeCountryController.scala
- app/forms/Countries.scala
- app/views/pensions/incomeFromOverseasPensions/PensionOverseasIncomeCountryView.scala.html
- it/controllers/pensions/incomeFromOverseasPensions/PensionOverseasIncomeCountryControllerSpec.scala
- test/services/CountryServiceTest.scala
Jira subtask: SASS-3247
Have you ...
Have you ...
Have you ...
Have you ...
> Sass 3247 fix

- app/common/MessageKeys.scala
- app/controllers/BaseYesNoController.scala
- app/controllers/BaseYesNoWithIndexController.scala
- app/controllers/pensions/overseas/incomeFromOverseasPension/ForeignTaxCreditReliefController.scala
- app/views/pensions/overseas/incomeFromOverseasPension/ForeignTaxCreditReliefView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/overseas/incomeFromOverseasPension/ForeignTaxCreditReliefControllerISpec.scala
Jira subtask: SASS-3340
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3340 Implemented Foreign Tax Credit Relief page

- app/controllers/pensions/unauthorisedPayments/UkPensionSchemeDetailsController.scala
- app/views/pensions/unauthorisedPayments/UkPensionSchemeDetails.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/unauthorisedPayments/UkPensionSchemeDetailsControllerISpec.scala
- it/utils/PageUrls.scala
Jira subtask: SASS-2957
Have you ...
Have you ...
Have you ...
Have you ...
> SASS 2957 - Add pension reference summary page for unauth pensions

- app/controllers/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAController.scala
- app/controllers/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAViewHelper.scala
- app/utils/CYABaseHelper.scala
- app/views/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAView.scala.html
- app/views/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAViewHelper.scala
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAControllerISpec.scala
- it/utils/PageUrls.scala
- test/controllers/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAViewHelperTest.scala
Jira subtask: SASS-4079
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-4079] Initial commit for Check income from overseas pensions page

- app/controllers/predicates/ActionsProvider.scala
- app/controllers/predicates/EndOfYearFilterAction.scala
- app/controllers/predicates/TaxYearAction.scala
- app/controllers/predicates/UserPriorDataRequestRefinerAction.scala
- app/controllers/predicates/UserSessionDataRequestRefinerAction.scala
- app/models/requests/UserPriorDataRequest.scala
- app/models/requests/UserSessionDataRequest.scala
- app/utils/TaxYearHelper.scala
- test/builders/UserBuilder.scala
- test/controllers/predicates/ActionsProviderSpec.scala
- test/controllers/predicates/EndOfYearFilterActionSpec.scala
- test/controllers/predicates/UserPriorDataRequestRefinerActionSpec.scala
- test/controllers/predicates/UserSessionDataRequestRefinerActionSpec.scala
- test/support/mocks/MockPensionSessionService.scala
Infrastructure to support Play! ActionRefiner pattern for controllers
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-4134: ActionRefiner Support

- app/controllers/pensions/incomeFromOverseasPensions/ForeignTaxCreditReliefController.scala
- app/controllers/pensions/incomeFromOverseasPensions/PensionPaymentsController.scala
- app/controllers/pensions/incomeFromOverseasPensions/PensionSchemeSummaryController.scala
- app/controllers/pensions/incomeFromOverseasPensions/SpecialWithholdingTaxController.scala
- app/models/pension/pages/OverseasPensionSchemeSummaryPage.scala
- app/views/pensions/incomeFromOverseasPensions/ForeignTaxCreditReliefView.scala.html
- app/views/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAViewHelper.scala
- app/views/pensions/incomeFromOverseasPensions/PensionPaymentsView.scala.html
- app/views/pensions/incomeFromOverseasPensions/PensionsSchemeSummary.scala.html
- app/views/pensions/incomeFromOverseasPensions/SpecialWithholdingTaxView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/config/MessagesSpec.scala
- test/support/ViewUnitTest.scala
- test/utils/FakeRequestProvider.scala
- test/views/OverseasPensionSchemeSummaryTestSupport.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3265, SASS-4184][AS] Pension scheme summary - Income from overseas pensions

- app/forms/Countries.scala
Have you ...
Have you ...
Have you ...
Have you ...
> Initial commit for fixing issue

- app/views/pensions/unauthorisedPayments/WhereAnyOfTheUnauthorisedPaymentsView.scala.html
- it/controllers/pensions/unauthorisedPayments/WhereAnyOfTheUnauthorisedPaymentsControllerISpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS 4239]  Were any of the unauthorised payments from a UK pension scheme - No Pre-filling on the page

- app/controllers/pensions/transferIntoOverseasPensions/OverseasTransferChargePaidController.scala
- app/forms/FormsProvider.scala
- app/models/pension/charges/TransfersIntoOverseasPensionsViewModel.scala
- app/models/pension/pages/OverseasTransferChargePaidPage.scala
- app/services/OverseasTransferChargesService.scala
- app/views/pensions/transferIntoOverseasPensions/OverseasTransferChargesPaidView.scala.html
- conf/app.routes
- it/controllers/pensions/transferIntoOverseasPensions/OverseasTransferChargePaidControllerISpec.scala
- test/builders/TransfersIntoOverseasPensionsViewModelBuilder.scala
- test/models/OverseasTransferChargePaidPageSpec.scala
- test/services/OverseasTransferChargesServiceSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3297 - Implemented OverseasTransferChargePaidController

- app/controllers/pensions/shortServiceRefunds/TaxableRefundAmountController.scala
- app/forms/FormsProvider.scala
- app/views/pensions/OverseasPensionsSummaryView.scala.html
- app/views/pensions/shortServiceRefunds/TaxableRefundAmountView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/OverseasPensionsSummaryControllerISpec.scala
- it/controllers/pensions/shortServiceRefunds/TaxableRefundAmountISpec.scala
- it/utils/PageUrls.scala
- test/views/OverseasPensionTransferTaxChargeSpec.scala
- test/views/shortServiceRefunds/ShortServiceTaxableRefundAmountSpec.scala
Jira subtask: [SASS-3319](https://jira.tools.tax.service.gov.uk/browse/SASS-3319)
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3319] Create Page: "Did you get a short service refund?" - Overseas Pensions/Short service refunds

- app/config/AppConfig.scala
- app/config/ConfigKeys.scala
- app/connectors/PensionsConnector.scala
- app/connectors/httpParsers/PensionChargesSessionHttpParser.scala
- app/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAController.scala
- app/models/APIErrorBodyModel.scala
- app/models/mongo/DatabaseError.scala
- app/models/pension/charges/CreateUpdatePensionChargesRequestModel.scala
- app/models/pension/charges/UnauthorisedPaymentsViewModel.scala
- app/services/PensionChargesService.scala
- app/utils/FutureEitherOps.scala
- conf/application.conf
- it/connectors/PensionsConnectorISpec.scala
- it/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAControllerISpec.scala
- it/helpers/WireMockHelper.scala
- it/utils/IntegrationTest.scala
- test/config/MockPensionsConnector.scala
- test/services/PensionsChargesServiceSpec.scala
Jira subtask: SASS-3446
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3446 - Implemented call to pension backend

- app/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAController.scala
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3446 - Fix CYA issue

- app/controllers/package.scala
- app/controllers/pensions/shortServiceRefunds/ShortServicePensionsSchemeController.scala
- app/controllers/pensions/shortServiceRefunds/TaxOnShortServiceRefundController.scala
- app/controllers/pensions/transferIntoOverseasPensions/OverseasTransferChargePaidController.scala
- app/forms/FormsProvider.scala
- app/models/pension/AllPensionsData.scala
- app/models/pension/charges/ShortServiceRefundsViewModel.scala
- app/models/pension/pages/shortServiceRefunds/TaxOnShortServiceRefundPage.scala
- app/services/ShortServiceRefundsService.scala
- app/utils/FutureEitherOps.scala
- app/views/pensions/shortServiceRefunds/TaxPaidOnShortServiceRefundView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/connectors/PensionsConnectorISpec.scala
- it/controllers/ControllerSpec.scala
- it/controllers/pensions/shortServiceRefunds/ShortServicePensionsSchemeControllerISpec.scala
- it/controllers/pensions/shortServiceRefunds/TaxOnShortServiceRefundControllerISpec.scala
- it/utils/PageUrls.scala
- test/builders/ShortServiceRefundsViewModelBuilder.scala
- test/services/ShortServiceRefundServiceSpec.scala
- test/views/shortServiceRefunds/TaxOnShortServiceRefundSpec.scala
Jira subtask: SASS-4527
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3323] - Initial commit for "Did a UK pension scheme pay tax on the short service refunds?"

- app/controllers/pensions/shortServiceRefunds/RefundSummaryController.scala
- app/views/pensions/shortServiceRefunds/RefundSummaryView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/shortServiceRefunds/RefundSummaryControllerISpec.scala
- it/controllers/pensions/transferIntoOverseasPensions/TransferChargeSummaryControllerISpec.scala
- it/utils/PageUrls.scala
- test/builders/PensionsUserDataBuilder.scala
- test/views/shortServiceRefunds/RefundSummaryViewSpec.scala
Jira subtask: SASS-3330-4451
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3330-4451 Implemented short service refund summary page

- app/controllers/pensions/shortServiceRefunds/RemoveRefundSchemeController.scala
- app/views/pensions/shortServiceRefunds/RefundSummaryView.scala.html
- app/views/pensions/shortServiceRefunds/RemoveRefundSchemeView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/ControllerSpec.scala
- it/controllers/pensions/shortServiceRefunds/RemoveRefundSchemeControllerISpec.scala
- test/views/shortServiceRefunds/RefundSummaryViewSpec.scala
- test/views/shortServiceRefunds/RemoveRefundSchemeViewSpec.scala
Jira subtask: SASS-4548
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-4548 Implemented remove refund scheme page

- app/views/pensions/incomeFromOverseasPensions/PensionsSchemeSummary.scala.html
- test/views/OverseasPensionSchemeSummarySpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3448] - Initial commit for fixing button text

- app/controllers/pensions/transferIntoOverseasPensions/TransferIntoOverseasPensionCYAViewHelper.scala
- app/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAViewHelper.scala
- app/utils/CYABaseHelper.scala
- test/controllers/pensions/transferIntoOverseasPensions/TransferIntoOverseasPensionCYAViewHelperSpec.scala
- test/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAViewSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-4176] - Initial commit for fixing bug

- app/controllers/pensions/PensionsSummaryController.scala
- it/controllers/pensions/PensionsSummaryControllerISpec.scala
Revert
Have you ...
Have you ...
Have you ...
Have you ...
> revert-SASS-4493: Pensions Summary - Initialise Pensions Session Data

- app/connectors/PensionsConnector.scala
- app/connectors/httpParsers/PensionIncomeSessionHttpParser.scala
- app/controllers/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAController.scala
- app/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAController.scala
- app/models/pension/charges/IncomeFromOverseasPensionsViewModel.scala
- app/models/pension/income/PensionIncome.scala
- app/services/PensionIncomeService.scala
- it/controllers/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAControllerISpec.scala
- it/utils/IntegrationTest.scala
- test/builders/IncomeTaxUserDataBuilder.scala
- test/config/MockPensionsConnector.scala
- test/services/PensionsIncomeServiceSpec.scala
Jira subtask: SASS-3449
Have you ...
Have you ...
Have you ...
Have you ...
> Sass 3449 Save Income for overseas pensions CYA to backend

- app/controllers/pensions/shortServiceRefunds/NonUkTaxRefundsController.scala
- app/controllers/pensions/shortServiceRefunds/ShortServicePensionsSchemeController.scala
- app/controllers/pensions/shortServiceRefunds/TaxOnShortServiceRefundController.scala
- app/controllers/pensions/shortServiceRefunds/TaxableRefundAmountController.scala
- app/utils/StatusHelper.scala
- app/views/pensions/shortServiceRefunds/RefundSummaryView.scala.html
- it/controllers/pensions/OverseasPensionsSummaryControllerISpec.scala
- it/controllers/pensions/shortServiceRefunds/NonUkTaxRefundsControllerISpec.scala
- it/controllers/pensions/shortServiceRefunds/ShortServicePensionsSchemeControllerISpec.scala
- it/controllers/pensions/shortServiceRefunds/TaxOnShortServiceRefundControllerISpec.scala
- test/views/shortServiceRefunds/RefundSummaryViewSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-4474] - Initial commit for Navigation for Short Service page

- app/controllers/pensions/incomeFromOverseasPensions/PensionPaymentsController.scala
- app/controllers/pensions/incomeFromPensions/PensionAmountController.scala
- app/controllers/pensions/lifetimeAllowances/PensionTakenAnotherWayAmountController.scala
- app/forms/FormsProvider.scala
- app/forms/OptionalTupleAmountForm.scala
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromOverseasPensions/PensionPaymentsControllerISpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3992] - Update Pension payments - Income from overseas pensions

- app/controllers/pensions/paymentsIntoOverseasPensions/SF74ReferenceController.scala
- app/forms/FormsProvider.scala
- app/forms/SF74ReferenceForm.scala
- app/views/pensions/paymentsIntoOverseasPensions/SF74ReferenceView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/paymentsIntoOverseasPensions/SF74ReferenceControllerISpec.scala
- it/utils/PageUrls.scala
- test/views/paymentsIntoOverseasPensions/SF74ReferenceViewSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-2589] - Initial commit for Create SF74 reference page

- conf/messages
- conf/messages.cy
Updates to message.cy and correct alignment with messages
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-4556: Welsh Translations For Pensions - Common Messages

- app/controllers/pensions/paymentsIntoOverseasPensions/PensionsCustomerReferenceNumberController.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/QOPSReferenceController.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/SF74ReferenceController.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/UntaxedEmployerPaymentsController.scala
- app/forms/FormsProvider.scala
- app/models/pension/AllPensionsData.scala
- app/models/pension/charges/PaymentsIntoOverseasPensionsViewModel.scala
- app/models/pension/pages/UntaxedEmployerPayments.scala
- app/services/PaymentsIntoOverseasPensionsService.scala
- app/views/pensions/paymentsIntoOverseasPensions/UntaxedEmployerPaymentsView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/ControllerSpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/PensionsCustomerReferenceNumberControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/QOPSReferenceControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/SF74ReferenceControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/UntaxedEmployerPaymentsControllerISpec.scala
- it/utils/PageUrls.scala
- test/builders/PaymentsIntoOverseasPensionsViewModelBuilder.scala
- test/models/UntaxedEmployerPaymentsPageSpec.scala
- test/views/paymentsIntoOverseasPensions/UntaxedEmployerControllerSpec.scala
Jira subtask: SASS-3099
Have you ...
Have you ...
Have you ...
Have you ...
> Sass 3099 - Implement Untaxed Employments Page

- app/views/pensions/incomeFromPensions/UkPensionSchemePaymentsView.scala.html
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromPensions/UkPensionSchemePaymentsControllerISpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> edit page content

- app/controllers/pensions/paymentsIntoOverseasPensions/ReliefsSchemeSummaryController.scala
- app/views/pensions/paymentsIntoOverseasPensions/ReliefSchemeSummaryView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/paymentsIntoOverseasPensions/ReliefSchemeSummaryControllerISpec.scala
- it/utils/PageUrls.scala
- test/builders/PaymentsIntoOverseasPensionsViewModelBuilder.scala
- test/views/paymentsIntoOverSeasPensions/ReliefSchemeSummaryViewSpec.scala
Jira subtask:[ [SASS-3243]](https://jira.tools.tax.service.gov.uk/browse/SASS-3243)
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3243] Create ''Schemes with untaxed employer payments'' page - Payments into overseas pensions

- app/controllers/pensions/paymentsIntoOverseasPensions/PensionReliefTypeController.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/QOPSReferenceController.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/ReliefsSchemeDetailsHelper.scala
- app/views/pensions/paymentsIntoOverseasPensions/QOPSReferenceView.scala.html
- conf/app.routes
- it/controllers/pensions/incomeFromOverseasPensions/PensionOverseasIncomeCountryControllerSpec.scala
- it/controllers/pensions/incomeFromOverseasPensions/TaxableAmountControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/IncomeFromPensionsSummaryControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/PensionSchemeTaxReferenceLifetimeControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/EmployerPayOverseasPensionControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/PensionsCustomerReferenceNumberControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/PensionsReliefControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/QOPSReferenceControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/TaxEmployerPaymentsControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/NoSurchargeAmountControllerISpec.scala
- it/utils/CommonUtils.scala
- it/utils/PageUrls.scala
- test/controllers/pensions/paymentsIntoOverseasPensions/ReliefsSchemeDetailsHelperSpec.scala
- test/views/paymentsIntoOverseasPensions/ReliefsSchemeDetailsViewSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-4550] Add QOPS entry field

- app/controllers/pensions/paymentsIntoOverseasPensions/PensionReliefTypeController.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/ReliefsSchemeDetailsHelper.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/SF74ReferenceController.scala
- app/views/pensions/paymentsIntoOverseasPensions/SF74ReferenceView.scala.html
- conf/app.routes
- it/controllers/pensions/paymentsIntoOverseasPensions/PensionsReliefControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/ReliefSchemeSummaryControllerISpec.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/SF74ReferenceControllerISpec.scala
- it/utils/PageUrls.scala
- test/controllers/pensions/paymentsIntoOverseasPensions/ReliefsSchemeDetailsHelperSpec.scala
- test/views/paymentsIntoOverSeasPensions/ReliefsSchemeDetailsViewSpec.scala
- test/views/paymentsIntoOverseasPensions/SF74ReferenceViewSpec.scala
Jira subtask: SASS-4762
Have you ...
Have you ...
Have you ...
Have you ...
> Upgrade Payment into Overseas pensions - SF74 reference Page

- app/views/pensions/PensionsSummaryView.scala.html
- it/controllers/pensions/PensionsSummaryControllerISpec.scala
Jira subtask: SASS-2585
Have you ...
Have you ...
Have you ...
Have you ...
> Update 'Pensions' landing page

- app/controllers/pensions/incomeFromPensions/PensionAmountController.scala
- it/controllers/pensions/incomeFromPensions/PensionAmountControllerISpec.scala
Jira subtask: [SASS-3789](https://jira.tools.tax.service.gov.uk/browse/SASS-3789)
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3789] Single Amount Is Not Pre-populated On Page: 'How much pension did you get paid?'

- app/controllers/pensions/lifetimeAllowances/PensionLumpSumDetailsController.scala
- app/forms/FormsProvider.scala
- app/views/pensions/lifetimeAllowances/PensionLumpSumDetailsView.scala.html
- it/controllers/pensions/lifetimeAllowances/PensionLumpSumDetailsControllerISpec.scala
Jira subtask: [SASS-3785](https://jira.tools.tax.service.gov.uk/browse/SASS-3785)
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3785] Single Amount Is Not Pre-populated On Page: 'Your pension lump sum'

- app/models/pension/charges/UnauthorisedPaymentsViewModel.scala
- app/services/PensionChargesService.scala
- test/services/PensionsChargesServiceSpec.scala
- test/services/PensionsIncomeServiceSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> SASS 4685 -FE Fix for bug

- app/controllers/pensions/lifetimeAllowances/AboveAnnualLifetimeAllowanceController.scala
- app/controllers/pensions/lifetimeAllowances/AnnualAndLifetimeAllowanceCYAViewHelper.scala
- app/controllers/pensions/lifetimeAllowances/AnnualLifetimeAllowanceGatewayController.scala
- app/controllers/pensions/lifetimeAllowances/LifeTimeAllowanceAnotherWayController.scala
- app/views/pensions/PensionsSummaryView.scala.html
- app/views/pensions/lifetimeAllowances/AboveAnnualLifetimeAllowanceView.scala.html
- app/views/pensions/lifetimeAllowances/LifeTimeAllowanceAnotherWayView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/PensionsSummaryControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/AboveAnnualLifetimeAllowanceControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/AnnualLifetimeAllowanceCYAControllerISpec.scala
- test/views/AnnualLifetimeAllowanceGatewaySpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-3929] Upgrade Page: 'Have you gone above your lifetime allowance?'

- conf/messages.cy
- it/controllers/pensions/lifetimeAllowances/AboveAnnualLifetimeAllowanceControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/AnnualLifetimeAllowanceCYAControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/LifeTimeAllowanceAnotherWayControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/PensionLumpSumControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/PensionLumpSumDetailsControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/PensionSchemeTaxReferenceLifetimeControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/PensionTakenAnotherWayAmountControllerISpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-4769] Welsh translations - Pensions Lifetime Allowances

- conf/messages.cy
- it/controllers/pensions/unauthorisedPayments/NoSurchargeAmountControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/RemovePSTRControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/SurchargeAmountControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/UkPensionSchemeDetailsControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/WhereAnyOfTheUnauthorisedPaymentsControllerISpec.scala
- test/views/BenefitsFromSchemeSpec.scala
Jira subtask: SASS-4773
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-4773 Welsh translations

- app/models/pension/AllPensionsData.scala
- app/models/pension/charges/PensionSavingsTaxCharges.scala
- app/models/pension/charges/PensionSchemeUnauthorisedPayments.scala
- app/models/pension/charges/UnauthorisedPaymentsViewModel.scala
- app/models/pension/income/PensionIncome.scala
- app/services/PensionIncomeService.scala
- it/controllers/pensions/lifetimeAllowances/AnnualLifetimeAllowanceCYAControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAControllerISpec.scala
- it/utils/PensionDataStubs.scala
- test/builders/PensionIncomeViewModelBuilder.scala
- test/builders/PensionSavingTaxChargesBuilder.scala
- test/builders/PensionSchemeUnauthorisedPaymentsBuilder.scala
- test/services/PensionsIncomeServiceSpec.scala
Jira subtask: SASS-4685
Have you ...
Have you ...
Have you ...
Have you ...
> SASS 4685 - Updated Pension Models to be the same as API

- app/forms/PensionSchemeTaxReferenceForm.scala
- it/controllers/pensions/annualAllowances/PensionSchemeTaxReferenceControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/PensionSchemeTaxReferenceLifetimeControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/UnauthorisedPensionSchemeTaxReferenceControllerISpec.scala
- test/forms/PSTRFormSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-4538] Amend PSTR Form regex

- app/views/pensions/incomeFromOverseasPensions/CountrySummaryList.scala.html
- conf/app.routes
- it/controllers/pensions/incomeFromOverseasPensions/CountrySummaryListControllerISpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-4823] Add a scheme with overseas pension income

- app/controllers/pensions/paymentsIntoOverseasPensions/RemoveReliefSchemeController.scala
- app/services/EmploymentPensionService.scala
- app/views/pensions/incomeFromOverseasPensions/PensionOverseasIncomeCountryView.scala.html
- app/views/pensions/paymentsIntoOverseasPensions/DoubleTaxationAgreementView.scala.html
- app/views/pensions/shortServiceRefunds/ShortServicePensionsSchemeView.scala.html
- app/views/pensions/transferIntoOverseasPensions/TransferPensionsSchemeView.scala.html
- app/views/templates/Head.scala.html
- project/AppDependencies.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-4986] Upgrade hmrcPlayVersion to 7.7.0

- app/views/pensions/incomeFromPensions/UkPensionIncomeSummary.scala.html
- it/controllers/pensions/incomeFromPensions/UkPensionIncomeSummaryControllerISpec.scala
Jira subtask: SASS-4796
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-4796 Add a scheme - Other UK pensions

- app/controllers/pensions/lifetimeAllowances/PensionProviderPaidTaxController.scala
- it/controllers/ControllerSpec.scala
- it/controllers/pensions/lifetimeAllowances/PensionProviderPaidTaxControllerISpec.scala
Jira subtask: SASS-5105
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-5105 Upgrade "Pension Provider Tax Payment Amount" Page

- app/controllers/pensions/incomeFromOverseasPensions/RemoveOverseasIncomeSchemeController.scala
- app/views/pensions/incomeFromOverseasPensions/CountrySummaryList.scala.html
- app/views/pensions/incomeFromOverseasPensions/RemoveOverseasIncomeSchemeView.html
- app/views/pensions/incomeFromOverseasPensions/RemoveOverseasIncomeSchemeView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/incomeFromOverseasPensions/CountrySummaryListControllerISpec.scala
- it/controllers/pensions/incomeFromOverseasPensions/RemoveOverseasIncomeSchemeControllerISpec.scala
- it/utils/PageUrls.scala
- test/builders/IncomeFromOverseasPensionsViewModelBuilder.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-4716] Create 'Remove Pension scheme' page

- app/views/pensions/annualAllowances/PensionSchemeTaxReferenceView.scala.html
- app/views/pensions/lifetimeAllowances/PensionSchemeTaxReferenceLifetimeView.scala.html
- conf/messages
- conf/messages.cy
- it/controllers/pensions/annualAllowances/PensionSchemeTaxReferenceControllerISpec.scala
- test/config/MessagesSpec.scala
Jira subtask: SASS-3419
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3419 Pensions annual allowance Upgrade Page

- app/models/IncomeTaxUserData.scala
- app/models/pension/PensionCYABaseModel.scala
- app/models/pension/charges/CreateUpdatePensionChargesRequestModel.scala
- app/models/pension/charges/OverseasPensionContributions.scala
- app/models/pension/charges/PensionContributions.scala
- app/models/pension/charges/PensionSavingsTaxCharges.scala
- app/models/pension/charges/PensionSchemeOverseasTransfers.scala
- app/models/pension/charges/PensionSchemeUnauthorisedPayments.scala
- app/models/pension/charges/ShortServiceRefundsViewModel.scala
- app/models/pension/charges/TransfersIntoOverseasPensionsViewModel.scala
- app/services/PensionChargesConnectorHelper.scala
- app/services/PensionChargesService.scala
- app/services/PensionConnectorHelper.scala
- it/controllers/pensions/shortServiceRefunds/ShortServiceRefundsCYAControllerISpec.scala
- test/models/pension/charges/CreateUpdatePensionChargesRequestModelSpec.scala
- test/services/PensionsChargesServiceSpec.scala
Jira subtask: SASS-5048
Have you ...
Have you ...
Have you ...
Have you ...
> Sass 5048 - Update CYA submission for pension charges request models 

- app/connectors/PensionsConnector.scala
- app/connectors/httpParsers/DeletePensionIncomeHttpParser.scala
- app/models/pension/income/PensionIncome.scala
- app/services/PensionIncomeConnectorHelper.scala
- app/services/PensionIncomeService.scala
- app/services/PensionOverseasPaymentService.scala
- build.sbt
- test/builders/PensionIncomeBuilder.scala
- test/models/pension/income/CreateUpdatePensionIncomeRequestModelSpec.scala
- test/services/PensionsIncomeServiceSpec.scala
- test/services/PensionsPaymentsOverseasServiceSpec.scala
Jira subtask: SASS-5074
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-5074 - Implemented pension income helper changes

- app/controllers/pensions/lifetimeAllowances/AnnualAndLifetimeAllowanceCYAViewHelper.scala
- app/controllers/pensions/lifetimeAllowances/LifetimePstrSummaryController.scala
- app/controllers/pensions/lifetimeAllowances/PensionSchemeTaxReferenceLifetimeController.scala
- app/views/pensions/annualAllowances/PstrSummaryView.scala.html
- app/views/pensions/lifetimeAllowances/LifetimePstrSummaryView.scala.html
- build.sbt
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/annualAllowances/LifetimePstrSummaryControllerISpec.scala
- it/controllers/pensions/annualAllowances/PstrSummaryControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/AnnualLifetimeAllowanceCYAControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/LifetimePstrSummaryControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/PensionSchemeTaxReferenceLifetimeControllerISpec.scala
- it/utils/PageUrls.scala
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3623: Introduce Page: 'Pension schemes that paid or agreed to pay lifetime allowance tax'

- app/common/MessageKeys.scala
- app/controllers/pensions/annualAllowances/AboveReducedAnnualAllowanceController.scala
- app/controllers/pensions/annualAllowances/AnnualAllowanceCYAController.scala
- app/controllers/pensions/annualAllowances/AnnualAllowanceCYAViewHelper.scala
- app/controllers/pensions/annualAllowances/PensionProviderPaidTaxController.scala
- app/controllers/pensions/annualAllowances/ReducedAnnualAllowanceController.scala
- app/controllers/pensions/lifetimeAllowances/AnnualAndLifetimeAllowanceCYAViewHelper.scala
- app/forms/FormsProvider.scala
- app/models/pension/charges/PensionAnnualAllowancesViewModel.scala
- app/views/pensions/annualAllowances/AnnualAllowancesCYAView.scala.html
- app/views/pensions/annualAllowances/PensionProviderPaidTaxView.scala.html
- app/views/pensions/annualAllowances/PstrSummaryView.scala.html
- app/views/pensions/annualAllowances/ReducedAnnualAllowanceView.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/pensions/annualAllowances/AboveReducedAnnualAllowanceControllerISpec.scala
- it/controllers/pensions/annualAllowances/AnnualAllowanceCYAControllerISpec.scala
- it/controllers/pensions/annualAllowances/PensionProviderPaidTaxControllerISpec.scala
- it/controllers/pensions/annualAllowances/PstrSummaryControllerISpec.scala
- it/controllers/pensions/annualAllowances/ReducedAnnualAllowanceControllerISpec.scala
- it/controllers/pensions/incomeFromOverseasPensions/SpecialWithholdingTaxControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/AnnualLifetimeAllowanceCYAControllerISpec.scala
- it/controllers/pensions/transferIntoOverseasPensions/OverseasPensionTransferTaxChargeSchemeISpec.scala
- it/controllers/pensions/unauthorisedPayments/SurchargeAmountControllerISpec.scala
- it/utils/PageUrls.scala
- test/config/MessagesSpec.scala
- test/support/ViewHelper.scala
- test/views/pensions/annualAllowances/AnnualAllowanceCYAViewSpec.scala
- test/views/pensions/annualAllowances/PensionProviderPaidTaxViewSpec.scala
Page creation, development and tests for AnnualAllowanceCYAController Reworked and added PensionProviderPaidTaxController from the lifetime allowance package completed the wiring up the routing for the annual allowance journey
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-2470: Update Page: "Check your annual allowances"

- app/connectors/PensionsConnector.scala
- app/connectors/httpParsers/DeletePensionChargesHttpParser.scala
- app/connectors/httpParsers/DeletePensionIncomeHttpParser.scala
- app/connectors/httpParsers/DeletePensionReliefsHttpParser.scala
- app/models/pension/reliefs/Reliefs.scala
- app/services/PensionReliefsConnectorHelper.scala
- test/models/pension/reliefs/CreateUpdatePensionReliefsRequestModelSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-5076 - Added Pension Reliefs connector helper

- app/views/pensions/annualAllowances/PstrSummaryView.scala.html
- conf/messages
- conf/messages.cy
- it/controllers/pensions/annualAllowances/PstrSummaryControllerISpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-5279] Alternative format for PSTR summary page - Annual Allowance

- app/services/PensionOverseasPaymentService.scala
- app/services/PensionReliefsService.scala
- it/controllers/pensions/incomeFromOverseasPensions/CountrySummaryListControllerISpec.scala
- it/controllers/pensions/paymentsIntoPensions/PaymentsIntoPensionsCYAControllerISpec.scala
- test/builders/ReliefsBuilder.scala
- test/config/MockPensionsConnector.scala
- test/models/pension/reliefs/ReliefsSpec.scala
- test/services/PensionOverseasPaymentServiceSpec.scala
- test/services/PensionReliefsServiceSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-5080] Handling No Journey submission - Pension Reliefs

- app/controllers/pensions/unauthorisedPayments/NoSurchargeAmountController.scala
- app/controllers/pensions/unauthorisedPayments/NonUKTaxOnAmountNotResultedInSurchargeController.scala
- app/controllers/pensions/unauthorisedPayments/NonUKTaxOnAmountResultedInSurchargeController.scala
- app/controllers/pensions/unauthorisedPayments/RemovePSTRController.scala
- app/controllers/pensions/unauthorisedPayments/SurchargeAmountController.scala
- app/controllers/pensions/unauthorisedPayments/UkPensionSchemeDetailsController.scala
- app/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsCYAController.scala
- app/controllers/pensions/unauthorisedPayments/UnauthorisedPensionSchemeTaxReferenceController.scala
- app/controllers/pensions/unauthorisedPayments/WereAnyOfTheUnauthorisedPaymentsController.scala
- app/models/pension/charges/UnauthorisedPaymentsViewModel.scala
- app/services/redirects/UnauthorisedPaymentsRedirects.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-5356] Fix Unauthorised journey CYA isFinished check error

- conf/application.conf
revert CSP
Have you ...
Have you ...
Have you ...
Have you ...
> revert-SASS-3410: Revert Fix Misconfigured Content Security Policy

- app/controllers/pensions/lifetimeAllowances/LifetimeAllowanceCYAController.scala
- app/models/pension/charges/PensionLifetimeAllowancesViewModel.scala
- app/services/PensionChargesService.scala
- it/controllers/pensions/lifetimeAllowances/LifetimeAllowanceCYAControllerISpec.scala
Jira subtask: SASS-5322
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-5322: Implement save for lifetime allowance CYA

- app/models/pension/charges/PensionAnnualAllowancesViewModel.scala
amended PensionAnnualAllowancesViewModel.toPensionSavingsTaxCharges
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-3445: Implement Saving For 'Check Annual Allowances' CYA Page

- app/controllers/pensions/incomeFromPensions/StatePensionCYAController.scala
- app/controllers/pensions/shortServiceRefunds/ShortServiceRefundsCYAController.scala
- app/controllers/predicates/auditActions/AuditActionsProvider.scala
- app/controllers/predicates/auditActions/PensionsAuditAction.scala
- app/controllers/predicates/auditActions/package.scala
- app/models/audit/IncomeFromStatePensionsAudit.scala
- it/controllers/pensions/incomeFromPensions/StatePensionCYAControllerISpec.scala
- test/controllers/predicates/auditActions/AuditActionsProviderSpec.scala
Jira subtask: SASS-5060
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-5060] Propose view, create and amend for Income from pensions - Check your state pension

- app/controllers/pensions/paymentsIntoOverseasPensions/PaymentsIntoOverseasPensionsCYAController.scala
- app/controllers/predicates/auditActions/AuditActionsProvider.scala
- app/controllers/predicates/auditActions/PensionsAuditAction.scala
- app/controllers/predicates/auditActions/package.scala
- app/models/audit/PaymentsIntoOverseasPensionsAudit.scala
- it/controllers/pensions/paymentsIntoOverseasPensions/PaymentsIntoOverseasPensionsCYAControllerISpec.scala
- test/controllers/predicates/auditActions/AuditActionsProviderSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-5182] Audit events - Payments Into Overseas Pensions

- app/controllers/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAController.scala
- app/controllers/predicates/auditActions/AuditActionsProvider.scala
- app/controllers/predicates/auditActions/PensionsAuditAction.scala
- app/controllers/predicates/auditActions/package.scala
- app/models/audit/IncomeFromOverseasPensionsAudit.scala
- app/views/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAView.scala.html
- it/controllers/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAControllerISpec.scala
- test/controllers/predicates/auditActions/AuditActionsProviderSpec.scala
Jira subtask: SASS-5183
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-5183] Propose view, create and amend for income from overseas pensions

- app/controllers/pensions/annualAllowances/AnnualAllowanceCYAController.scala
- app/controllers/predicates/auditActions/AuditActionsProvider.scala
- app/controllers/predicates/auditActions/PensionsAuditAction.scala
- app/controllers/predicates/auditActions/package.scala
- app/models/audit/AnnualAllowancesAudit.scala
- it/controllers/pensions/annualAllowances/AnnualAllowanceCYAControllerISpec.scala
- test/controllers/predicates/auditActions/AuditActionsProviderSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-5179] Audit events - Annual Allowances

- app/controllers/pensions/incomeFromPensions/UkPensionIncomeCYAController.scala
- app/controllers/pensions/lifetimeAllowances/LifetimeAllowanceCYAController.scala
- app/controllers/pensions/shortServiceRefunds/ShortServiceRefundsCYAController.scala
- app/controllers/predicates/auditActions/AuditActionsProvider.scala
- app/controllers/predicates/auditActions/PensionsAuditAction.scala
- app/controllers/predicates/auditActions/package.scala
- app/models/audit/LifetimeAllowancesAudit.scala
- app/models/audit/UkPensionIncomeAudit.scala
- app/services/PensionConnectorHelper.scala
- app/views/pensions/incomeFromPensions/UkPensionIncomeCYAView.scala.html
- it/controllers/pensions/incomeFromOverseasPensions/IncomeFromOverseasPensionsCYAControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/StatePensionCYAControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/UkPensionIncomeCYAControllerISpec.scala
- it/controllers/pensions/lifetimeAllowances/LifetimeAllowanceCYAControllerISpec.scala
- it/controllers/pensions/transferIntoOverseasPensions/OverseasPensionTransferTaxChargeSchemeISpec.scala
- test/builders/ClaimCYAModelBuilder.scala
- test/controllers/predicates/auditActions/AuditActionsProviderSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-5178-5180] Audit events - Lifetime Allowances & Income from other UK pensions

- app/controllers/pensions/annualAllowances/AboveReducedAnnualAllowanceController.scala
- app/controllers/pensions/annualAllowances/PensionProviderPaidTaxController.scala
- app/controllers/pensions/annualAllowances/ReducedAnnualAllowanceController.scala
- app/controllers/pensions/incomeFromOverseasPensions/CountrySummaryListController.scala
- app/controllers/pensions/incomeFromOverseasPensions/PensionSchemeSummaryController.scala
- app/controllers/pensions/incomeFromOverseasPensions/RemoveOverseasIncomeSchemeController.scala
- app/controllers/pensions/lifetimeAllowances/RemoveLifetimeAllowancePstrController.scala
- it/controllers/pensions/annualAllowances/PensionProviderPaidTaxControllerISpec.scala
- it/controllers/pensions/incomeFromPensions/PensionSchemeSummaryControllerISpec.scala
Jira subtask: SASS-5537
Have you ...
Have you ...
Have you ...
Have you ...
> SASS- 5537 Remove In Year checks from Pensions journeys

- app/controllers/pensions/annualAllowances/AnnualAllowanceCYAViewHelper.scala
- conf/messages
- conf/messages.cy
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-6103] Add change link hidden messages

- app/views/pensions/paymentsIntoOverseasPensions/PensionReliefTypeView.scala.html
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-5973] Add values to PensionReliefTypeView

- app/controllers/pensions/incomeFromPensions/StatePensionController.scala
- app/controllers/pensions/incomeFromPensions/StatePensionLumpSumController.scala
- app/controllers/pensions/incomeFromPensions/StatePensionStartDateController.scala
- app/controllers/pensions/incomeFromPensions/TaxPaidOnStatePensionLumpSumController.scala
- app/controllers/pensions/incomeFromPensions/package.scala
- app/models/pension/statebenefits/IncomeFromPensionsViewModel.scala
- app/models/pension/statebenefits/StateBenefitViewModel.scala
- app/services/redirects/StatePensionPages.scala
- it/controllers/pensions/incomeFromPensions/StatePensionLumpSumControllerISpec.scala
- test/controllers/pensions/incomeFromPensions/incomeFromPensionsSpec.scala
- test/models/pension/statebenefits/IncomeFromPensionsViewModelSpec.scala
- test/models/pension/statebenefits/StateBenefitViewModelSpec.scala
Fixing up some boolean logic that is wrong causing the page navigation to be incorrect and break the pipeline as a result.
> NOJIRA - Fix pensions pipeline due to failing state pensions tests

- app/connectors/PensionsConnector.scala
- app/connectors/httpParsers/GetAllJourneyStatusesHttpParser.scala
- app/models/mongo/Mtditid.scala
- app/services/PensionSessionService.scala
- app/utils/TaxYearHelper.scala
- it/connectors/PensionsConnectorISpec.scala
- it/controllers/pensions/incomeFromPensions/StatePensionCYAControllerISpec.scala
- it/controllers/pensions/unauthorisedPayments/UnauthorisedPaymentsControllerISpec.scala
- it/helpers/WireMockHelper.scala
- it/utils/CommonUtils.scala
- it/utils/IntegrationTest.scala
- test/config/MockPensionsConnector.scala
- test/services/PensionSessionServiceSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-8074] Get all journey statuses from backend for Summary pages

- app/config/AppConfig.scala
- app/connectors/PensionsConnector.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/EmployerPayOverseasPensionController.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/PaymentIntoPensionSchemeController.scala
- app/controllers/pensions/paymentsIntoOverseasPensions/PaymentsIntoOverseasPensionsCYAController.scala
- app/controllers/predicates/auditActions/AuditActionsProvider.scala
- app/models/pension/charges/PaymentsIntoOverseasPensionsViewModel.scala
- app/services/PensionSessionService.scala
- app/services/redirects/PaymentsIntoOverseasPensionsRedirects.scala
- app/viewmodels/JourneyStatusSummaryViewModel.scala
- app/views/pensions/paymentsIntoOverseasPensions/ReliefSchemeSummaryView.scala.html
- conf/app.routes
- test/services/redirects/PaymentsIntoOverseasPensionsRedirectsSpec.scala
- test/views/pensions/paymentsIntoOverseasPensions/ReliefSchemeSummaryViewSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> SASS-8221 Get empty journey data from the frontend

- app/controllers/pensions/paymentsIntoPensions/PaymentsIntoPensionsCYAController.scala
- app/models/pension/reliefs/PaymentsIntoPensionsViewModel.scala
- test/builders/PaymentsIntoPensionVewModelBuilder.scala
- test/controllers/ControllerSpecBase.scala
- test/controllers/pensions/paymentsIntoPensions/PaymentsIntoPensionsCYAControllerSpec.scala
- test/models/pension/reliefs/PaymentsIntoPensionsViewModelSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-8255] Re-add ExcludeJourney method to PaymentsIntoPensions submission

- app/controllers/pensions/IncomeFromPensionsSummaryController.scala
- app/models/redirects/AppLocations.scala
- app/services/PensionSessionService.scala
- app/utils/StatusHelper.scala
- app/viewmodels/JourneyStatusSummaryViewModel.scala
- app/views/pensions/incomeFromPensions/PensionSchemeSummaryView.scala.html
- app/views/pensions/incomeFromPensions/UkPensionIncomeSummary.scala.html
- conf/app.routes
- test/viewmodels/JourneyStatusSummaryViewModelSpec.scala
Have you ...
Have you ...
Have you ...
Have you ...
> [SASS-7134] Fix CYA redirection from summary page links

- app/common/Enrolments.scala
- app/config/AppConfig.scala
- app/config/Modules.scala
- app/controllers/predicates/actions/AuthorisedAction.scala
- app/models/User.scala
- conf/application.conf
- it/utils/IntegrationTest.scala
- test/controllers/LanguageSwitchControllerSpec.scala
- test/controllers/predicates/actions/AuthorisedActionSpec.scala
- test/support/mocks/MockAuthorisedAction.scala
- test/support/mocks/MockErrorHandler.scala
- test/utils/UnitTest.scala
App config change completed in https://github.com/hmrc/app-config-base/pull/11426
> SASS-10726: Add secondary agent auth logic

- app/config/AppConfig.scala
- app/connectors/SessionDataConnector.scala
- app/connectors/httpParsers/SessionDataHttpParser.scala
- app/models/session/SessionData.scala
- build.sbt
- conf/application.conf
- it/connectors/SessionDataConnectorISpec.scala
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
app-config-base:
- https://github.com/hmrc/app-config-base/pull/12130
> [SASS-11693] Add connector to income-tax-session-data
